# Generated by Django 2.2.9 on 2020-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tjd_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('staff_id', models.CharField(default='', max_length=20, unique=True, verbose_name='工号')),
                ('jineng', models.CharField(max_length=100, verbose_name='人员技能')),
                ('ruzhitime', models.DateField(verbose_name='入职时间')),
                ('fazhan', models.CharField(max_length=30, verbose_name='发展方向')),
                ('diqu', models.CharField(default='', max_length=20, verbose_name='所在地')),
                ('dengji', models.CharField(default='', max_length=20, verbose_name='等级')),
                ('zhuangtai', models.IntegerField(choices=[(0, '待分配'), (1, '项目中')], default=0, verbose_name='状态')),
            ],
        ),
    ]
