# Generated by Django 2.2.9 on 2020-02-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manageradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tjd_staff',
            name='jineng',
            field=models.CharField(max_length=100, verbose_name='人员技能'),
        ),
    ]
