# Generated by Django 2.2.9 on 2020-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manageradmin', '0002_auto_20200204_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tjd_staff',
            name='fazhan',
            field=models.CharField(max_length=30, verbose_name='发展方向'),
        ),
    ]
