# Generated by Django 2.2.9 on 2020-02-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmsqd',
            name='xmjl_staff_id',
            field=models.CharField(max_length=20, verbose_name='项目经理工号'),
        ),
    ]
