# Generated by Django 2.2.9 on 2020-02-18 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmsqd',
            name='fprystr',
        ),
    ]
